# Generated by Django 3.1.3 on 2020-12-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('mana', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('art_path', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('feature', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('mana', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('login', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('resourses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rarity', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('cost_create', models.IntegerField()),
                ('cost_destruct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('hp', models.IntegerField()),
                ('art_path', models.CharField(blank=True, max_length=50, null=True)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.heroclass')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.heropower')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.player')),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.typecard')),
            ],
        ),
        migrations.CreateModel(
            name='CardPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.player')),
            ],
        ),
        migrations.CreateModel(
            name='CardMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.card')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.deck')),
            ],
        ),
        migrations.CreateModel(
            name='CardClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.card')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.heroclass')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardGame.rarity'),
        ),
    ]
