# Generated by Django 3.1.3 on 2020-12-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0002_auto_20201214_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddeck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.deck'),
        ),
        migrations.AlterField(
            model_name='cardmechanic',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='cardmechanic',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.mechanic'),
        ),
        migrations.AlterField(
            model_name='cardplayer',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='cardplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.player'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.typecard'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.hero'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.player'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='class_field',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.RESTRICT, to='cardGame.heroclass'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.heropower'),
        ),
    ]
