# Generated by Django 3.1.3 on 2020-12-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0003_auto_20201214_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.player')),
            ],
        ),
    ]
