# Generated by Django 3.1.3 on 2020-12-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0004_heroplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.rarity'),
        ),
        migrations.AlterField(
            model_name='cardclass',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.deck'),
        ),
        migrations.AlterField(
            model_name='cardplayer',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.card'),
        ),
        migrations.AlterField(
            model_name='cardplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.player'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.hero'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.player'),
        ),
        migrations.AlterField(
            model_name='heroplayer',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.hero'),
        ),
        migrations.AlterField(
            model_name='heroplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardGame.player'),
        ),
    ]
